apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: noelalonso1/eureka-server
        ports:
        - name: eureka-port
          containerPort: 8761

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbit-mq-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbit-mq
    spec:
      hostname: rabbitmq
      containers:
      - name: rabbit-mq
        image: rabbitmq:3.7.8-management-alpine
        ports:
        - containerPort: 5672
        - containerPort: 15672

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-client-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: eureka-client
    spec:
      containers:
      - name: eureka-client
        image: noelalonso1/eureka-client
        imagePullPolicy: Always
        ports:
        - name: spr-boot-port
          containerPort: 8080

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ribbon-client-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ribbon-client
    spec:
      containers:
      - name: ribbon-client
        image: noelalonso1/ribbon-client
        ports:
        - name: spr-boot-port-2
          containerPort: 8090

---
# DEPLOYMENT: Hystrix - console
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hystrix-console-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ribbon-client
    spec:
      containers:
      - name: hystrix-console
        image: noelalonso1/hystrix-console
        ports:
        - name: hyst-cons-port
          containerPort: 8100

---
# INGRESS !!
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-rules
spec:
  rules:
  - host: hello.noelalonso.tk
    http:
      paths:
      - path: /
        backend:
          serviceName: helloworld-service
          servicePort: 80
  - host: noelalonso.tk
    http:
      paths:
      - path: /
        backend:
          serviceName: helloworld-service
          servicePort: 80
  - host: www.noelalonso.tk
    http:
      paths:
      - path: /
        backend:
          serviceName: helloworld-service
          servicePort: 80
  - host: hystrix-console.noelalonso.tk
    http:
      paths:
      - path: /
        backend:
          serviceName: helloworld-service
          servicePort: 80
  - host: eureka.noelalonso.tk
    http:
      paths:
      - path: /
        backend:
          serviceName: eureka-server-service
          servicePort: 8761
  - host: client.noelalonso.tk
    http:
      paths:
      - path: /
        backend:
          serviceName: ribbon-client-service
          servicePort: 8090
  - host: rabbit.noelalonso.tk
    http:
      paths:
      - path: /
        backend:
          serviceName: ribbon-client-service
          servicePort: 15672

---
# SERVICE: ingress-controller (controller creado con https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/mandatory.yaml)
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
#    - name: https
#      port: 443
#      targetPort: https
  
---
# SERVICE: eureka-server
apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
spec:
  ports:
  - port: 8761
    targetPort: eureka-port
    protocol: TCP
  selector:
    app: eureka-server
  type: ClusterIP

---
# SERVICE: ribbon-client
apiVersion: v1
kind: Service
metadata:
  name: ribbon-client-service
spec:
  ports:
  - port: 8090
    targetPort: spr-boot-port-2
    protocol: TCP
  selector:
    app: ribbon-client
  type: ClusterIP

---
# SERVICE: rabbit-mq
apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq-service
spec:
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: rabbit1
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: rabbit2
  selector:
    app: rabbit-mq
  type: ClusterIP