apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: noelalonso1/eureka-server
        ports:
        - name: eureka-port
          containerPort: 8761

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbit-mq-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbit-mq
    spec:
      hostname: rabbitmq
      containers:
      - name: rabbit-mq
        image: rabbitmq:3.7.8-management-alpine
        ports:
        - containerPort: 5672
        - containerPort: 15672

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-client-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: eureka-client
    spec:
      containers:
      - name: eureka-client
        image: noelalonso1/eureka-client
        imagePullPolicy: Always
        ports:
        - name: spr-boot-port
          containerPort: 8080

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ribbon-client-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ribbon-client
    spec:
      containers:
      - name: ribbon-client
        image: noelalonso1/ribbon-client
        ports:
        - name: spr-boot-port-2
          containerPort: 8090

---
# DEPLOYMENT: Hystrix - console
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hystrix-console-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ribbon-client
    spec:
      containers:
      - name: hystrix-console
        image: noelalonso1/hystrix-console
        ports:
        - name: hyst-cons-port
          containerPort: 8100

---
# INGRESS CONTOLLER
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress-controller-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-ingress-controller
    spec:
      containers:
        - name: nginx-ingress-lb
          image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.17.1
          args:
            - /nginx-ingress-controller
            - --default-backend-service=$(POD_NAMESPACE)/echoheaders-default
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
          - name: http
            containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP

---
# INGRESS !!
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-rules
spec:
  rules:
  - host: hello.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: helloworld-service
          servicePort: 80

---
# SERVICE: ingress-controller
apiVersion: v1
kind: Service
metadata:
  name: ingress-controller-service
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: nginx-ingress-controller
  type: LoadBalancer
  
---
# SERVICE: eureka-server
apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
spec:
  ports:
  - port: 8761
    targetPort: eureka-port
    protocol: TCP
  selector:
    app: eureka-server
  type: ClusterIP

---
# SERVICE: ribbon-client
apiVersion: v1
kind: Service
metadata:
  name: ribbon-client-service
spec:
  ports:
  - port: 8090
    targetPort: spr-boot-port-2
    protocol: TCP
  selector:
    app: ribbon-client
  type: ClusterIP

---
# SERVICE: rabbit-mq
apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq-service
spec:
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: rabbit1
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: rabbit2
  selector:
    app: rabbit-mq
  type: ClusterIP