spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: ${vcap.services.zipkin-server.credentials.uri:http://zipkin-server:9411}
    sender:
      type: web
  rabbitmq:
    host: rabbit-mq-service
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-service:8761/eureka
#      defaultZone: http://localhost:8761/eureka

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
#       include: '*'
        include: hystrix.stream, info, health, refresh
#        include: info, health, refresh

ribbon:
  serverListRefreshInterval: 3000
  eureka:
    enabled: true
   
#a-bootiful-client: 
#  ribbon:
#    eureka:
#      enabled: false
#      listOfServers: localhost:8080,localhost:8081
#      ServerListRefreshInterval: 15000
  

  