spring:
  application:
    name: hystrix-console
  rabbitmq:
    host: maquinavirtual
    
server:
  port: 8100

# Configurar turbine
#turbine:
#  aggregator:
#    clusterConfig: CLIENT-RIBBON-BALANCER-NOEL, A-BOOTIFUL-CLIENT
#  appConfig: client-ribbon-balancer-noel, a-bootiful-client
  
turbine:
  aggregator:
    clusterConfig: DEFAULT
  appConfig: client-ribbon-balancer-noel,a-bootiful-client
  clusterNameExpression: "'DEFAULT'"

  
# Configurar el Discovery Client
eureka:
  client: 
    enabled: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
